## origin_matrix.csv
大元のmatrix  
- user, itemそれぞれ10,000件

In [16]:
pd.read_csv("../dataset/origin_matrix.csv".format(dir_name), index_col=0)

,item_0,item_1,item_2,item_3,item_4,item_5,item_6,item_7,item_8,item_9,...,item_9990,item_9991,item_9992,item_9993,item_9994,item_9995,item_9996,item_9997,item_9998,item_9999
user_0,0.597859,0.544633,0.553456,0.692309,0.773937,0.740925,0.244659,0.548349,0.425090,0.470206,...,0.517317,0.742676,0.597787,0.234464,0.577333,0.681520,0.790216,0.648305,0.591606,0.533985
user_1,0.631693,0.494963,0.506338,0.540617,0.623003,0.608106,0.623928,0.583911,0.830369,0.602293,...,0.680373,0.502455,0.579182,0.358047,0.702315,0.627378,0.661064,0.751437,0.572844,0.609761
user_2,0.470106,0.444696,0.548824,0.465589,0.723931,0.564409,0.517046,0.426072,0.616797,0.496631,...,0.532052,0.515031,0.563999,0.468768,0.645146,0.557231,0.792037,0.599915,0.664522,0.719183
user_3,0.484086,0.242101,0.287123,0.628113,0.697996,0.708477,0.638900,0.588499,0.679644,0.695768,...,0.709227,0.436744,0.515394,0.351010,0.541739,0.573953,0.891930,0.676803,0.491495,0.713302
user_4,0.662280,0.596565,0.550002,0.724620,0.607163,0.583914,0.753945,0.387664,0.536198,0.651687,...,0.690932,0.556325,0.660682,0.517959,0.500379,0.662294,0.653107,0.459986,0.629991,0.705510
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
user_9995,0.666565,0.714915,0.386881,0.726423,0.595893,0.635913,0.804104,0.591460,0.745079,0.554362,...,0.798201,0.335004,0.678911,0.784210,0.437605,0.556226,0.612934,0.522837,0.476000,0.499873
user_9996,0.691493,0.489992,0.627829,0.673182,0.643931,0.782119,0.639690,0.417889,0.670743,0.580744,...,0.688798,0.601752,0.417489,0.435945,0.370768,0.575158,0.712698,0.479993,0.528218,0.568222
user_9997,0.619993,0.439615,0.519811,0.627810,0.582972,0.629249,0.758556,0.587390,0.572455,0.686231,...,0.517000,0.433820,0.514588,0.320282,0.416237,0.614721,0.803545,0.541787,0.664770,0.546721
user_9998,0.667605,0.562455,0.595646,0.794400,0.773192,0.437349,0.709425,0.402751,0.702373,0.583125,...,0.776866,0.548878,0.685914,0.662048,0.444686,0.790529,0.598878,0.408135,0.614884,0.632430
user_9999,0.660582,0.392131,0.411871,0.566217,0.665676,0.699381,0.585222,0.557555,0.683427,0.748103,...,0.595307,0.640155,0.600594,0.422565,0.488582,0.558769,0.709289,0.663325,0.548528,0.674348

## item_profile.arr
itemのプロファイルベクトル
- 10次元, 10,000行

In [21]:
with open("../dataset/item_profile.arr", 'rb') as f:
    item_prof_vecs = pkl.load(f)
item_prof_vecs

array([[0.4511865 , 0.28481063, 0.39723662, ..., 0.108227  , 0.03633724,
        0.61655848],
       [0.20827496, 0.47110508, 0.43195544, ..., 0.16738015, 0.22184325,
        0.12998785],
       [0.02138166, 0.20084144, 0.53852064, ..., 0.05533108, 0.47815168,
        0.58533806],
       ...,
       [0.2472275 , 0.71763699, 0.16212096, ..., 0.72006631, 0.67477528,
        0.95676   ],
       [0.51511075, 0.00561289, 0.86100054, ..., 0.82606425, 0.91811212,
        0.36104953],
       [0.70755658, 0.2842581 , 0.74588256, ..., 0.18986716, 0.44896772,
        0.77424414]])

## user_profile
userのプロファイルベクトル
- user_profile_all.arr：10次元, 10,000行
- user_profile_trn.arr：10次元,  8,000行
- user_profile_tst.arr：10次元,  2,000行

In [26]:
with open("../dataset/user_profile_all.arr", 'rb') as f:
    user_prof_vecs = pkl.load(f)

In [30]:
user_prof_vecs

array([[0.43674225, 0.34761431, 0.33960129, ..., 0.15628846, 0.79106709,
        0.6777633 ],
       [0.74889296, 0.61712061, 0.57148413, ..., 0.22455184, 0.64429664,
        0.46379366],
       [0.51963223, 0.39318432, 0.49852632, ..., 0.62178875, 0.87515208,
        0.25382387],
       ...,
       [0.37974706, 0.37287571, 0.51124222, ..., 0.50154303, 0.49572842,
        0.53060526],
       [0.18792503, 0.57080421, 0.86265828, ..., 0.7692315 , 0.11030527,
        0.21877194],
       [0.44142044, 0.54060818, 0.63412628, ..., 0.33367273, 0.59939259,
        0.68025962]])

## del_10per（10%欠損データ）
- del_10per
    - matrix_trn.csv（学習用評価値テーブル）
    - matrix_tst.csv（テスト用評価値テーブル）
    - train_data.csv（学習データ）
    - test_data.csv（テストデータ）

![](../image/dataset.png)

In [31]:
del_rate = 0.1
dir_name = "del_{}per".format(int(del_rate*100))

df_trn = pd.read_csv("../dataset/{}/matrix_trn.csv".format(dir_name), index_col=0)
df_tst = pd.read_csv("../dataset/{}/matrix_tst.csv".format(dir_name), index_col=0)
train_dataset = pd.read_csv("../dataset/{}/train_data.csv".format(dir_name), header=None)
test_dataset  = pd.read_csv("../dataset/{}/test_data.csv".format(dir_name), header=None)

### matrix_trn.csv
- user数：8000

In [35]:
df_trn

,item_0,item_1,item_2,item_3,item_4,item_5,item_6,item_7,item_8,item_9,...,item_9990,item_9991,item_9992,item_9993,item_9994,item_9995,item_9996,item_9997,item_9998,item_9999
user_0,0.597859,0.544633,0.553456,NaN,0.773937,0.740925,0.244659,0.548349,0.425090,0.470206,...,0.517317,0.742676,0.597787,0.234464,0.577333,0.681520,0.790216,0.648305,0.591606,0.533985
user_1,0.631693,0.494963,0.506338,0.540617,0.623003,0.608106,NaN,0.583911,0.830369,NaN,...,0.680373,0.502455,0.579182,0.358047,0.702315,NaN,0.661064,0.751437,0.572844,0.609761
user_2,0.470106,0.444696,0.548824,0.465589,0.723931,0.564409,0.517046,0.426072,0.616797,0.496631,...,0.532052,0.515031,NaN,0.468768,0.645146,0.557231,0.792037,0.599915,0.664522,0.719183
user_3,0.484086,0.242101,0.287123,0.628113,0.697996,NaN,0.638900,0.588499,0.679644,0.695768,...,0.709227,0.436744,0.515394,0.351010,0.541739,0.573953,0.891930,0.676803,0.491495,0.713302
user_4,0.662280,0.596565,0.550002,0.724620,0.607163,0.583914,0.753945,0.387664,0.536198,NaN,...,0.690932,0.556325,0.660682,0.517959,0.500379,0.662294,0.653107,0.459986,0.629991,0.705510
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
user_7995,0.532767,0.392432,NaN,0.677584,0.624572,0.731235,0.763950,0.640576,0.483227,0.639399,...,0.677162,0.396135,0.446960,0.419716,0.327348,0.551457,0.645927,0.594860,0.419840,0.596353
user_7996,0.467624,0.608212,0.602480,0.590725,0.684239,0.638297,0.503652,0.590589,0.709721,0.692876,...,0.680098,0.614869,0.572470,NaN,0.297747,0.598878,0.696927,0.508238,0.613456,0.518393
user_7997,0.646805,0.514029,0.435181,0.657214,0.762836,0.723522,0.758954,NaN,0.585347,0.655743,...,0.685544,0.537932,0.506047,0.492851,0.398596,0.671879,0.492758,0.592992,0.418916,0.590655
user_7998,0.559743,0.454107,0.466385,0.703248,0.602829,0.664837,0.624381,0.348708,0.751599,0.687346,...,0.541907,0.420786,0.612865,0.576922,0.368226,0.534525,NaN,0.577897,0.496726,0.527966
user_7999,0.640762,NaN,0.533780,0.482854,0.786901,0.704975,0.656906,0.455624,0.596557,0.591268,...,0.670831,0.429324,0.615993,0.381292,0.514439,0.336638,0.778124,0.576690,0.585331,0.413101

---
### matrix_tst.csv
- user：2000

In [34]:
df_tst

,item_0,item_1,item_2,item_3,item_4,item_5,item_6,item_7,item_8,item_9,...,item_9990,item_9991,item_9992,item_9993,item_9994,item_9995,item_9996,item_9997,item_9998,item_9999
user_0,0.784237,0.468585,NaN,0.610613,0.779784,0.658724,0.556801,0.570882,NaN,0.654900,...,0.613405,0.491018,0.601654,0.534332,0.443217,NaN,0.724505,0.636200,0.566232,0.935109
user_1,0.577248,0.491466,0.322680,0.385710,0.745878,0.725817,0.590712,0.714326,0.616473,0.483059,...,0.564750,0.431804,0.748542,0.429574,0.322836,0.690432,NaN,0.566839,0.611341,0.553181
user_2,0.750187,0.602279,0.484660,NaN,0.857112,0.664642,0.815056,0.607531,0.688216,0.600472,...,0.540980,0.440357,0.512827,0.493702,0.277846,0.615503,0.640384,NaN,0.539488,0.601120
user_3,0.829588,NaN,0.546749,0.718543,0.803562,0.696757,0.784118,0.522649,NaN,0.543130,...,NaN,0.501833,0.515403,0.466792,0.548404,0.709240,0.698373,0.588213,0.504574,0.783960
user_4,0.638348,0.677625,0.567107,0.805121,0.516420,0.594459,0.668904,0.512207,0.566980,0.718636,...,0.716646,NaN,0.819179,0.365742,0.369547,0.710062,0.658030,0.546967,0.553452,0.391439
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
user_1995,0.666565,0.714915,0.386881,0.726423,0.595893,NaN,0.804104,0.591460,0.745079,0.554362,...,0.798201,NaN,0.678911,0.784210,0.437605,0.556226,NaN,0.522837,0.476000,0.499873
user_1996,0.691493,0.489992,0.627829,0.673182,0.643931,0.782119,0.639690,0.417889,0.670743,0.580744,...,0.688798,0.601752,0.417489,0.435945,0.370768,0.575158,0.712698,0.479993,0.528218,NaN
user_1997,0.619993,NaN,0.519811,0.627810,0.582972,0.629249,0.758556,0.587390,0.572455,0.686231,...,0.517000,0.433820,0.514588,0.320282,0.416237,0.614721,0.803545,0.541787,0.664770,0.546721
user_1998,NaN,NaN,0.595646,0.794400,0.773192,0.437349,0.709425,0.402751,0.702373,NaN,...,0.776866,0.548878,0.685914,0.662048,0.444686,NaN,0.598878,NaN,0.614884,0.632430
user_1999,NaN,NaN,0.411871,0.566217,0.665676,0.699381,0.585222,0.557555,0.683427,0.748103,...,0.595307,0.640155,0.600594,0.422565,0.488582,NaN,0.709289,0.663325,NaN,0.674348

---
### train_data.csv
DeapLearningの学習用データ
- 1列目：userID（user_profile_trn.arrを参照）
- 2列目：itemID（item_profile.arrを参照）
- 3列目：評価値（教師ラベル）

In [33]:
train_dataset

             0     1         2
0            0     0  0.597859
1            0     1  0.544633
2            0     2  0.553456
3            0     4  0.773937
4            0     5  0.740925
...        ...   ...       ...
71999995  7999  9995  0.336638
71999996  7999  9996  0.778124
71999997  7999  9997  0.576690
71999998  7999  9998  0.585331
71999999  7999  9999  0.413101

[72000000 rows x 3 columns]

---
### test_data.csv
テストデータ
- 1列目：userID（DLはuser_profile_tst.arrを参照）
- 2列目：itemID（DLはitem_profile.arrを参照）
- 3列目：評価値（教師ラベル）

In [32]:
test_dataset

            0     1         2
0        1162   329  0.415992
1         552   119  0.309555
2         722  1225  0.506999
3         628  5212  0.634008
4         123  5418  0.668554
...       ...   ...       ...
1999995  1110   990  0.413208
1999996   242  7103  0.649912
1999997   706  3509  0.345793
1999998  1046  9626  0.584589
1999999   237  4825  0.641713

[2000000 rows x 3 columns]

In [17]:
import pandas as pd
pd.set_option("display.max_columns", 20)
pd.set_option("display.max_rows", 10)

import pickle as pkl